//COMMON
export const SET_IS_MOBILE = "SET_IS_MOBILE";

//LAYOUT
export const SET_SHOW_SIDEDRAWER = "SET_SHOW_SIDEDRAWER";

//ME
export const FETCH_TOPICS_START = "FETCH_TOPICS_START";
export const FETCH_TOPICS_SUCCESS = "FETCH_TOPICS_SUCCESS";
export const SELECT_TOPIC_ID = "SELECT_TOPIC_ID";
