//COMMON
export const SET_IS_MOBILE = "SET_IS_MOBILE";

//LAYOUT
export const SET_SHOW_SIDEDRAWER = "SET_SHOW_SIDEDRAWER";

//ME
export const FETCH_TOPICS_START = "FETCH_TOPICS_START";
export const FETCH_TOPICS_SUCCESS = "FETCH_TOPICS_SUCCESS";
export const SELECT_TOPIC_ID = "SELECT_TOPIC_ID";

//EXPERIENCE
export const FETCH_TECNOLOGIES_WITH_TEXT_START =
  "FETCH_TECNOLOGIES_WITH_TEXT_START";
export const FETCH_TECNOLOGIES_WITH_TEXT_SUCCESS =
  "FETCH_TECNOLOGIES_WITH_TEXT_SUCCESS";
export const FETCH_PROYECTS_IMG_WITH_TEXT_START =
  "FETCH_PROYECTS_IMG_WITH_TEXT_START";
export const FETCH_PROYECTS_IMG_WITH_TEXT_SUCCESS =
  "FETCH_PROYECTS_IMG_WITH_TEXT_SUCCESS";
export const SET_TOGGLE_HANDLER = "SET_TOGGLE_HANDLER";
